import type { Activity } from "@/types/activity";

export const mockActivities: Activity[] = [
  {
    id: "1",
    category: "Спорт",
    title: "Ищу напарника в зал",
    shortDate: "Сегодня · 19:00",
    fullDate: "Сегодня, 19:00",
    shortPlace: "Центр",
    fullPlace: "Центр города",
    format: "Офлайн",
    summary: "Тренировка на спину и руки. Уровень любой.",
    description: [
      "Тренировка на спину и руки.",
      "Подойдёт любой уровень подготовки.",
      "Без обязательств — просто потренируемся вместе.",
    ],
    participants: { current: 1, maximum: 2 },
    author: {
      id: "alex-smirnov",
      name: "Алексей Смирнов",
      faculty: "ИТИС · 2 курс",
      initial: "А",
    },
    publishedAt: "2026-10-09T09:25:00+03:00",
    likesCount: 12,
    commentsCount: 3,
  },
  {
    id: "2",
    category: "Проект",
    title: "Собираем команду на хакатон",
    shortDate: "Сб–Вс",
    fullDate: "Суббота и воскресенье",
    shortPlace: "Онлайн",
    fullPlace: "Онлайн, Discord",
    format: "Онлайн",
    summary: "Нужен дизайнер или фронтендер.",
    description: [
      "Собираем небольшую команду для участия в хакатоне.",
      "Ищем дизайнера или frontend-разработчика.",
      "Опыт необязателен — главное желание сделать рабочий проект.",
    ],
    participants: { current: 2, maximum: 4 },
    author: {
      id: "alina-valeeva",
      name: "Алина Валеева",
      faculty: "ИТИС · 1 курс",
      initial: "А",
    },
    publishedAt: "2026-10-09T08:10:00+03:00",
    likesCount: 21,
    commentsCount: 8,
    likedByCurrentUser: true,
  },
  {
    id: "3",
    category: "Игры",
    title: "Настольные игры после пар",
    shortDate: "Вчера · 18:30",
    fullDate: "Вчера, 18:30",
    shortPlace: "Кампус",
    fullPlace: "Студенческий кампус",
    format: "Офлайн",
    summary: "Собрались на пару партий после занятий.",
    description: [
      "Вечер настольных игр после пар.",
      "Играли в быстрые командные игры и знакомились.",
    ],
    participants: { current: 6, maximum: 6 },
    author: {
      id: "current-user",
      name: "Михаил Петров",
      faculty: "ИТИС · 1 курс",
      initial: "М",
    },
    publishedAt: "2026-10-08T14:30:00+03:00",
    likesCount: 17,
    commentsCount: 5,
    status: "Завершена",
  },
  {
    id: "4",
    category: "Учёба",
    title: "Разбираем React перед проектом",
    shortDate: "Пт · 17:30",
    fullDate: "Пятница, 17:30",
    shortPlace: "Библиотека",
    fullPlace: "Главная библиотека, 2 этаж",
    format: "Офлайн",
    summary: "Небольшая группа: компоненты, state и роутинг без лишней теории.",
    description: [
      "Собираемся на полтора-два часа и разбираем React на живом мини-проекте.",
      "Можно приходить с базовым JavaScript — остальное доберём по ходу.",
    ],
    participants: { current: 3, maximum: 6 },
    author: {
      id: "current-user",
      name: "Михаил Петров",
      faculty: "ИТИС · 1 курс",
      initial: "М",
    },
    publishedAt: "2026-10-07T19:20:00+03:00",
    likesCount: 9,
    commentsCount: 2,
  },
  {
    id: "5",
    category: "Прогулка",
    title: "Кто после пар пройтись по центру?",
    shortDate: "Сегодня · 20:15",
    fullDate: "Сегодня, 20:15",
    shortPlace: "Кремлёвская",
    fullPlace: "Встречаемся у главного входа",
    format: "Офлайн",
    summary: "Без маршрута и тайминга — просто пройтись и поболтать.",
    description: [
      "После длинного учебного дня хочется пройтись по центру.",
      "Темп спокойный, можно присоединиться по дороге.",
    ],
    participants: { current: 2, maximum: 5 },
    author: {
      id: "sofia-kim",
      name: "София Ким",
      faculty: "ИМО · 2 курс",
      initial: "С",
    },
    publishedAt: "2026-10-09T10:05:00+03:00",
    likesCount: 7,
    commentsCount: 1,
  },
];

export const welcomeActivityIds = ["1", "2"];
